---
title: "Quiz3"
author: "Mihai M. Craiu"
date: "14/7/2020"
output: pdf_document
---

# Question 1

The American Community Survey distributes downloadable data about United States communities. Download the 2006 microdata survey about housing for the state of Idaho using download.file() from here:

[data.csv](https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06hid.csv)

and load the data into R. The code book, describing the variable names is here:

[codebook.pdf](https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FPUMSDataDict06.pdf)

Create a logical vector that identifies the households on greater than 10 acres who sold more than $10,000 worth of agriculture products. Assign that logical vector to the variable agricultureLogical. Apply the which() function like this to identify the rows of the data frame where the logical vector is TRUE.

which(agricultureLogical)

What are the first 3 values that result?

```{R}

Q1url <- "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06hid.csv"
Q1 <- read.csv(Q1url)
head(Q1)

#Computing solution…

agricultureLogical <- Q1$ACR == 3 & Q1$AGS == 6
which(agricultureLogical)
```
Options:

*a. 125, 238,262*

b. 403, 756, 798

c. 236, 238, 262

d. 59, 460, 474


# Question 2

Using the jpeg package read in the following picture of your instructor into R

[picture.jpg](https://d396qusza40orc.cloudfront.net/getdata%2Fjeff.jpg)

Use the parameter native=TRUE. What are the 30th and 80th quantiles of the resulting data? (some Linux systems may produce an answer 638 different for the 30th quantile)

```{R}

# Loading package…

library(jpeg)

# Downloading file…

Q2Url <- "https://d396qusza40orc.cloudfront.net/getdata%2Fjeff.jpg"
Q2Path = 'C:/Users/Mihai/Desktop/Data_Science_JHU_Coursera/Getting_and_Cleaning_Data/Week_3/Q2.jpg'
download.file(Q2Url, Q2Path, mode = 'wb')
Q2 <- readJPEG(Q2Path, native = TRUE)

# Computing solution…

quantile(Q2, probs = c(0.3, 0.8))

```

‘some Linux systems may produce an answer 638 different for the 30th quantile.’

Mine is Linux, so…

```{R}

paste(quantile(Q2, probs = 0.3) - 638, quantile(Q2, probs = 0.8))

```
Options:

*a. -15259150 -10575416*

b. -10904118 -10575416

c. 10904118 -594524

d. -16776430 -15390165



# Question 3

Load the Gross Domestic Product data for the 190 ranked countries in this data set:

[https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv](https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv)

Load the educational data from this data set:

[https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FEDSTATS_Country.csv](https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FEDSTATS_Country.csv)

Match the data based on the country shortcode. How many of the IDs match?

Sort the data frame in descending order by GDP rank (so United States is last). What is the 13th country in the resulting data frame?

Original data sources:

http://data.worldbank.org/data-catalog/GDP-ranking-table

http://data.worldbank.org/data-catalog/ed-stats


```{R}

# Loading packages…

library(dplyr)
library(data.table)

# Download file…

Q3GDP_Url <- "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv"
Q3GDP_Path <- "C:/Users/Mihai/Desktop/Data_Science_JHU_Coursera/Getting_and_Cleaning_Data/Week_3/Q3GDP.csv"
Q3Edu_Url <- "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FEDSTATS_Country.csv"
Q3Edu_Path <- "C:/Users/Mihai/Desktop/Data_Science_JHU_Coursera/Getting_and_Cleaning_Data/Week_3/Q3Edu.csv"

download.file(Q3GDP_Url, Q3GDP_Path, method = "curl")
download.file(Q3Edu_Url, Q3Edu_Path, method = "curl")

# OR

#download.file(Q3GDP_Url, destfile = "./Gross_Domestic_Product.csv", method = "curl")
#download.file(Q3Edu_Url, destfile = "./Educational_data.csv.csv", method = "curl")


# Analyze the data…

Q3GDP <- fread(Q3GDP_Path, skip = 5, nrows = 190, select = c(1, 2, 4, 5), col.names = c("CountryCode", "Rank", "Economy", "Total"))
Q3Edu <- fread(Q3Edu_Path)

head(Q3GDP)


head(Q3Edu)


# Merging and sorting data…

Q3_Merge <- merge(Q3GDP, Q3Edu, by = 'CountryCode')
Q3_Merge <- Q3_Merge %>% arrange(desc(Rank))

head(Q3_Merge)


# Generating solution…


paste(nrow(Q3_Merge), " matches, 13th country is ", Q3_Merge$Economy[13])


```


Options:

a. 189 matches, 13th country is Spain

b. 234 matches, 13th country is St. Kitts and Nevis

c. 190 matches, 13th country is St. Kitts and Nevis

d. 190 matches, 13th country is Spain

*e. 189 matches, 13th country is St. Kitts and Nevis*

f. 234 matches, 13th country is Spain























