---
title: 'R Programming Assignment 1: Air Pollution'
author: "Mihai M. Craiu"
date: "29/6/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

For this first programming assignment you will write three functions that are meant to interact with dataset that accompanies this assignment. The dataset is contained in a zip file specdata.zip that you can download from the Coursera web site.

## Data
The zip file containing the data can be downloaded here:

## [specdata.zip](https://d396qusza40orc.cloudfront.net/rprog%2Fdata%2Fspecdata.zip)

The zip file contains 332 comma-separated-value (CSV) files containing pollution monitoring data for fine particulate matter (PM) air pollution at 332 locations in the United States. Each file contains data from a single monitor and the ID number for each monitor is contained in the file name. For example, data for monitor 200 is contained in the file “200.csv”. Each file contains three variables:

- Date: the date of the observation in YYYY-MM-DD format (year-month-day)

- sulfate: the level of sulfate PM in the air on that date (measured in micrograms per cubic meter)

- nitrate: the level of nitrate PM in the air on that date (measured in micrograms per cubic meter)

For this programming assignment you will need to unzip this file and create the directory ‘specdata’. Once you have unzipped the zip file, do not make any modifications to the files in the ‘specdata’ directory. In each file you’ll notice that there are many days where either sulfate or nitrate (or both) are missing (coded as NA). This is common with air pollution monitoring data in the United States.

# Solution

## First step

Directory have to be "C:/Users/Mihai/Desktop/Data_Science_JHU_Coursera/Rprogramming/Week_2/specdata/"

getwd()

setwd("C:/Users/Mihai/Desktop/Data_Science_JHU_Coursera/Rprogramming/Week_2/specdata/")

Now we have to create a variable whit .csv data
```{R}
getwd()
setwd("specdata")

getwd()

data <- read.csv("001.csv", header = T)
```

Now we are going to create 3 functions


## Part 1

The function ‘pollutantmean’ calculates the mean of a pollutant (sulfate or nitrate) across a specified list of monitors. The function ‘pollutantmean’ takes three arguments: ‘directory’, ‘pollutant’, and ‘id’. Given a vector monitor ID numbers, ‘pollutantmean’ reads that monitors’ particulate matter data from the directory specified in the ‘directory’ argument and returns the mean of the pollutant across all of the monitors, ignoring any missing values coded as NA.

pollutantmean <- function(directory, pollutant, id = 1:332) {

'directory' is a character vector of length 1 indicating
the location of the CSV files

'pollutant' is a character vector of length 1 indicating
the name of  the pollutant for which we will calcultate the
mean; either "sulfate" or "nitrate"

'id' is an integer vector indicating the monitor ID numbers
to be used

Return the mean of the pollutant across all monitors list
in the 'id' vector (ignoring NA values)
NOTE: Do not round the result
}

```{R}
setwd("specdata")

pollutantmean <- function(directory, pollutant, id=1:332){
  mylist <- list.files(path=directory, pattern=".csv")
  x <- numeric()
  for(i in id){
    mydata <- read.csv(mylist[i])
    x <- c(x, mydata[[pollutant]])
  }
  mean(x, na.rm=T)
}
#directory = "C:/Users/Mihai/Desktop/Data_Science_JHU_Coursera/Rprogramming/Week_2/specdata/"
```
You can see some example output from this function below. The function that you write should be able to match this output. Please save your code to a file named pollutantmean.R.

```{R}
setwd("specdata")

pollutantmean("C:/Users/Mihai/Desktop/Data_Science_JHU_Coursera/Rprogramming/Week_2/specdata/",
              "sulfate", 1:10)

pollutantmean("C:/Users/Mihai/Desktop/Data_Science_JHU_Coursera/Rprogramming/Week_2/specdata/",
              "nitrate", 70:72)

pollutantmean("C:/Users/Mihai/Desktop/Data_Science_JHU_Coursera/Rprogramming/Week_2/specdata/",
              "nitrate", 23)
```


## Part 2

The function ‘complete’ reads a directory full of files and reports the number of completely observed cases in each data file. The function should return a data frame where the first column is the name of the file and the second column is the number of complete cases.

complete <- function(directory, id = 1:332){

'director' is a character vector of length 1 indicating
the location of the CSV files

'id' is an integer vector indicating the monitor ID numbers
to be used

Return a data frame of the from:
id nobs
1  117
2  1041
...
where 'id' is the monitor ID number and 'nobs' is the
number of complete cases
}

```{R}
setwd("specdata")
complete <- function(directory, id=1:332){
  mylist <- list.files(path=directory, pattern=".csv")
  nobs <- numeric()
  for(i in id){
    mydata <- read.csv(mylist[i])
    mysum <- sum(complete.cases(mydata))
    nobs <- c(nobs, mysum)
  }
  data.frame(id, nobs)
}

#directory = "C:/Users/Mihai/Desktop/Data_Science_JHU_Coursera/Rprogramming/Week_2/specdata/"
```

You can see some example output from this function below. The function that you write should be able to match this output. Please save your code to a file named complete.R. To run the submit script for this part, make sure your working directory has the file complete.R in it.

```{R}
setwd("specdata")

complete("C:/Users/Mihai/Desktop/Data_Science_JHU_Coursera/Rprogramming/Week_2/specdata/", 1)
complete("C:/Users/Mihai/Desktop/Data_Science_JHU_Coursera/Rprogramming/Week_2/specdata/",
         c(2, 4, 8, 10, 12))
complete("C:/Users/Mihai/Desktop/Data_Science_JHU_Coursera/Rprogramming/Week_2/specdata/",
         30:25)
complete("C:/Users/Mihai/Desktop/Data_Science_JHU_Coursera/Rprogramming/Week_2/specdata/", 3)
```

## Part 3

The function ‘corr’ takes a directory of data files and a threshold for complete cases and calculates the correlation between sulfate and nitrate for monitor locations where the number of completely observed cases (on all variables) is greater than the threshold. The function should return a vector of correlations for the monitors that meet the threshold requirement. If no monitors meet the threshold requirement, then the function should return a numeric vector of length 0.

corr <- function(directory, threshold = 0){

'directory' is a character vector of length 1 indicating
the location of the CSV files

'threshold' is a numeric vector of length 1 indicating the 
number of completely observed observations (on all
variables) requi?red to compute the correlation between
nitrate and sulfate; the default is 0

Return a numeric vector of correlations
NOTE: Do not round the result!
}

```{R}
setwd("specdata")

corr <- function(directory, threshold = 0){
  mylist <- list.files(path=directory, pattern=".csv")
  df <- complete(directory)
  ids <- df[df["nobs"] > threshold, ]$id
  corrr <- numeric()
  for(i in ids){
    mydata <- read.csv(mylist[i])
    dff <- mydata[complete.cases(mydata), ]
    corrr <- c(corrr, cor(dff$sulfate, dff$nitrate))
  }
  return(corrr)
}

#directory = "C:/Users/Mihai/Desktop/Data_Science_JHU_Coursera/Rprogramming/Week_2/specdata/"
```

For this function you will need to use the 'cor' function in R which calculates the correlation between two vectors. Please read the help page for this function via '?cor' and make sure that you know how to use it.

You can see some example output from this function below. The function that you write should be able to approximately match this output. Note that because of how R rounds and presents floating point numbers, the output you generate may differ slightly from the example output. Please save your code to a file named corr.R. To run the submit script for this part, make sure your working directory has the file corr.R in it.

```{R}
setwd("specdata")

cr <- corr("C:/Users/Mihai/Desktop/Data_Science_JHU_Coursera/Rprogramming/Week_2/specdata/",
           150)
head(cr)

summary(cr)

cr_1<- corr("C:/Users/Mihai/Desktop/Data_Science_JHU_Coursera/Rprogramming/Week_2/specdata/",
            400)
head(cr_1)

summary(cr_1)

cr_2 <- corr("C:/Users/Mihai/Desktop/Data_Science_JHU_Coursera/Rprogramming/Week_2/specdata/",
             5000)
summary(cr_2)

length(cr)

cr_all <- corr("C:/Users/Mihai/Desktop/Data_Science_JHU_Coursera/Rprogramming/Week_2/specdata/")

summary(cr_all)

length(cr_all)

```

# Quiz Solutions

## Questions

### Q1. What value is returned by the following call to pollutantmean()? You should round your output to 3 digits.

```{R}
setwd("specdata")
pollutantmean("C:/Users/Mihai/Desktop/Data_Science_JHU_Coursera/Rprogramming/Week_2/specdata/",
              "sulfate", 1:10)
```

### Q2. What value is returned by the following call to pollutantmean()? You should round your output to 3 digits.

```{R}
setwd("specdata")
pollutantmean("C:/Users/Mihai/Desktop/Data_Science_JHU_Coursera/Rprogramming/Week_2/specdata/",
              "nitrate", 70:72)
```

### Q3. What value is returned by the following call to pollutantmean()? You should round your output to 3 digits.

```{R}
setwd("specdata")

pollutantmean("C:/Users/Mihai/Desktop/Data_Science_JHU_Coursera/Rprogramming/Week_2/specdata/",
              "sulfate",34)
```

### Q4. What value is returned by the following call to pollutantmean()? You should round your output to 3 digits.

```{R}
setwd("specdata")

pollutantmean("C:/Users/Mihai/Desktop/Data_Science_JHU_Coursera/Rprogramming/Week_2/specdata/",
              "nitrate")

round(pollutantmean("C:/Users/Mihai/Desktop/Data_Science_JHU_Coursera/Rprogramming/Week_2/specdata/", 
                    "nitrate"),3)
```

### Q5. What value is printed at end of the following code?
```{R}
setwd("specdata")

cc <- complete("C:/Users/Mihai/Desktop/Data_Science_JHU_Coursera/Rprogramming/Week_2/specdata/",
               c(6, 10, 20, 34, 100, 200, 310))
print(cc$nobs)
```
### Q6. What value is printed at end of the following code?
```{R}
setwd("specdata")

cc_1<- complete("C:/Users/Mihai/Desktop/Data_Science_JHU_Coursera/Rprogramming/Week_2/specdata/",
                54)
print(cc$nobs)
```

### Q7. What value is printed at end of the following code?
```{R}
setwd("specdata")

set.seed(42)
cc_2<-complete("C:/Users/Mihai/Desktop/Data_Science_JHU_Coursera/Rprogramming/Week_2/specdata/",
               331:1)
use<-sample(332,10)
print(cc_2[use,"nobs"])
```

### Q8. What value is printed at end of the following code?
```{R}
setwd("specdata")

cr<- corr("C:/Users/Mihai/Desktop/Data_Science_JHU_Coursera/Rprogramming/Week_2/specdata/")

cr<- sort(cr)
set.seed(868)
out<- round(cr[sample(length(cr),5)],4)
print(out)
```

### Q9. What value is printed at end of the following code?
```{R}
setwd("specdata")

cr <- corr("C:/Users/Mihai/Desktop/Data_Science_JHU_Coursera/Rprogramming/Week_2/specdata/",
           129)
cr <- sort(cr)                
n <- length(cr)                
set.seed(197)                
out <- c(n, round(cr[sample(n, 5)], 4))
print(out)
```

### Q10. What value is printed at end of the following code?
```{R}
setwd("specdata")

cr <- corr("C:/Users/Mihai/Desktop/Data_Science_JHU_Coursera/Rprogramming/Week_2/specdata/",
           2000)
n <- length(cr)
cr <- corr("C:/Users/Mihai/Desktop/Data_Science_JHU_Coursera/Rprogramming/Week_2/specdata/",
           1000)
cr <- sort(cr)
print(c(n, round(cr, 4)))
```

























